### PR TITLE
fix more than one day uptime print

### PR DESCRIPTION
**Pull request by illwieckz**
fix more than one day uptime print

### CODE REVIEW

**Comment by IngarKCT** [comment]
Doesn't seem to work as advertised on Arch Linux, most likely subtle differences in the uptime output. uptime -p seems a bit verbose, an alternative is to parse /proc/uptime

**Comment by illwieckz** [comment]
It looks like collapsing spaces before filtering is better.

Also, `uptime -p` does not work on all systems.

**Comment by illwieckz** [comment]
also, perhaps you don't mind the hours and minutes when it's in day

**Comment by IngarKCT** [comment]
Yeah that seems to work, great!

**Pull request merged**
